### PR TITLE
escape spaces as they are also reserved

### PR DESCRIPTION
**Pull request by armw4**
lanetix/issues#3582

This will result in a breaking change, so major will be bumped.

escape-space-caveat

### CODE REVIEW

**Comment by armw4** [comment]
@lanetix/engineers

**Comment by pythonesque** [comment]
:+1:

**Comment by Vanuan** [comment]
Is there a way for this behavior to be optional? I don't see the point in escaping spaces.

**Comment by Vanuan** [comment]
Currently I'm doing this:
```
esSanitize("big brown fox").replace(new RegExp('\ ', 'g'), " ");
```

which is kind of silly.

**Pull request merged**
